backend:
  name: github
  repo:  janKollars/gaertnerei-ruzicka
  branch: enable-netlifycms
media_folder: site/static/img
public_folder: /img
collections:
  - name: page
    label: Seiten
    folder: site/content
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Titel, name: title, widget: string }
      - { label: Inhalt, name: body, widget: markdown }

  - name: kraeuter
    label: Kr채uter
    folder: site/content/kraeuter
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Name2, name: name2, widget: string }
      - { label: Gattung, name: gattung, widget: string }
      - label: Preisklasse
        name: preis
        widget: select
        options: [A, B, C, D, E, F]
      - label: Jahr
        name: jahr
        widget: select
        options:
          - { label: einj채hrig, value: 1 }
          - { label: zweij채hrig, value: 2 }
          - { label: mehrj채hrig, value: m }
      - { label: winterhart, name: winter, widget: boolean }
      - label: Lichtbedarf
        name: licht
        widget: select
        options:
          - { label: absonnig, value: 1 }
          - { label: lichtschattig, value: 2 }
          - { label: halbschattig, value: 3 }
          - { label: vollschattig, value: 4 }
      - label: Wasserbedarf
        name: wasser
        widget: select
        options:
          - { label: viel, value: 1 }
          - { label: wenig, value: 2 }
          - { label: kein, value: 3 }
      - { label: Beschreibung, name: body, widget: markdown }
